### PR TITLE
IE compatibility

### PR DESCRIPTION
**Pull request by artemanufrij**
fix for #12

### CODE REVIEW

**Comment by artemanufrij** [comment]
hey @chryb could you check my PR please? We need it for project :).

Thank you very much!

**Comment by artemanufrij** [comment]
hey @chryb,

any news? :smiley:

**Comment by chryb** [comment]
I'll look into it today.

**Comment by artemanufrij** [comment]
thank you @chryb !

**Comment by chryb** [comment]
I've merged it and uploaded it on NPM. Please check if everything goes right.

**Comment by artemanufrij** [comment]
will do! I give you feedback tomorrow.

**Pull request merged**
