### PR TITLE
Added resize event

### PR DESCRIPTION
**Pull request by andreybutenko**
`this.handler.$emit('RESIZE')` triggers a resize on the C3 chart.

Updated readme and re-built `dist` file.

### CODE REVIEW

**Comment by chryb** [comment]
Thank you :) I think about to add a handler method like `this.handler.$emit('dispatch', (chart) => { ... })`. You can access the chart object directly. With that, I don't have to simulate the whole c3 api. What do you think about it?

**Comment by andreybutenko** [comment]
@chryb I think that would be super-useful!
With that, people won't need to set up a PR every time they need access to a new method ;)

**Comment by chryb** [comment]
True :) Fine, I will upload the new version soon.

**Comment by chryb** [comment]
Ok, I've uploaded it.

**Pull request merged**
